### ISSUE TITLE
Failed to import  installed Node

### ISSUE THREAD

**Issue by Lumabrik** [deroberon/demofusion-comfyui#6]
I have an import failure of the custom node once its installed. This isnt the portable version of Comfy, All the other installed custom nodes I have dont have this issue.  Thanks.

[!] DEPRECATION: torchsde 0.2.5 has a non-standard dependency specifier numpy>=1.19.*; python_version >= "3.7". pip 24.0 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of torchsde or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063
## [ERROR] Demofusion: Failed to install the GitPython package in the correct Python environment. Please install it manually in the appropriate environment. (You can seek help at https://app.element.io/#/room/%23comfyui_space%3Amatrix.org)
Traceback (most recent call last):
  File "C:\StableDiffusion\ComfyUI\custom_nodes\demofusion-comfyui\__init__.py", line 42, in <module>
    from .demofusion import NODE_CLASS_MAPPINGS
  File "C:\StableDiffusion\ComfyUI\custom_nodes\demofusion-comfyui\demofusion.py", line 19, in <module>
    from pipeline_demofusion_sdxl import DemoFusionSDXLStableDiffusionPipeline
  File "C:\StableDiffusion\ComfyUI\custom_nodes\demofusion-comfyui\pipeline_demofusion_sdxl.py", line 55, in <module>
    from .watermark import StableDiffusionXLWatermarker
ImportError: attempted relative import with no known parent package

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\StableDiffusion\ComfyUI\custom_nodes\demofusion-comfyui\__init__.py", line 52, in <module>
    from .demofusion import NODE_CLASS_MAPPINGS
  File "C:\StableDiffusion\ComfyUI\custom_nodes\demofusion-comfyui\demofusion.py", line 19, in <module>
    from pipeline_demofusion_sdxl import DemoFusionSDXLStableDiffusionPipeline
  File "C:\StableDiffusion\ComfyUI\custom_nodes\demofusion-comfyui\pipeline_demofusion_sdxl.py", line 55, in <module>
    from .watermark import StableDiffusionXLWatermarker
ImportError: attempted relative import with no known parent package

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\StableDiffusion\ComfyUI\custom_nodes\demofusion-comfyui\__init__.py", line 58, in <module>
    from .demofusion import NODE_CLASS_MAPPINGS
  File "C:\StableDiffusion\ComfyUI\custom_nodes\demofusion-comfyui\demofusion.py", line 19, in <module>
    from pipeline_demofusion_sdxl import DemoFusionSDXLStableDiffusionPipeline
  File "C:\StableDiffusion\ComfyUI\custom_nodes\demofusion-comfyui\pipeline_demofusion_sdxl.py", line 55, in <module>
    from .watermark import StableDiffusionXLWatermarker
ImportError: attempted relative import with no known parent package
## Demofusion: installing dependencies done.
Skip C:\StableDiffusion\ComfyUI\custom_nodes\demofusion-comfyui module for custom nodes due to the lack of NODE_CLASS_MAPPINGS.

**Comment by deroberon** [comment]
Yeah, the non portable envs are super heterogenous, and so, super difficult to debug. 

But I believe I could spot what could have been causing issues in yours. I just did a commit that, if I was correct in my toughts, should solve the problem. 

Please, could you try to install it again and let me know if everything went fine?

**Comment by Lumabrik** [comment]
Thanks, thats great, its working now after reinstalling it.

**Comment by deroberon** [comment]
Great to hear that :)
